# CMake generated Testfile for 
# Source directory: /homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/cython
# Build directory: /homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(periodic_cubical_complex_barcode_persistence_from_perseus_file_example_py_test "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython" "/homes/rhu/Documents/phd_projects/kernelgformula/g_env/bin/python" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/cython/example/periodic_cubical_complex_barcode_persistence_from_perseus_file_example.py" "--no-barcode" "-f" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/data/bitmap/CubicalTwoSphere.txt")
set_tests_properties(periodic_cubical_complex_barcode_persistence_from_perseus_file_example_py_test PROPERTIES  WORKING_DIRECTORY "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython")
add_test(random_cubical_complex_persistence_example_py_test "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython" "/homes/rhu/Documents/phd_projects/kernelgformula/g_env/bin/python" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/cython/example/random_cubical_complex_persistence_example.py" "10" "10" "10")
set_tests_properties(random_cubical_complex_persistence_example_py_test PROPERTIES  WORKING_DIRECTORY "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython")
add_test(rips_complex_diagram_persistence_from_distance_matrix_file_example_py_test "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython" "/homes/rhu/Documents/phd_projects/kernelgformula/g_env/bin/python" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/cython/example/rips_complex_diagram_persistence_from_distance_matrix_file_example.py" "--no-diagram" "-f" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/data/distance_matrix/lower_triangular_distance_matrix.csv" "-e" "12.0" "-d" "3")
set_tests_properties(rips_complex_diagram_persistence_from_distance_matrix_file_example_py_test PROPERTIES  WORKING_DIRECTORY "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython")
add_test(rips_complex_diagram_persistence_from_off_file_example_py_test "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython" "/homes/rhu/Documents/phd_projects/kernelgformula/g_env/bin/python" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/cython/example/rips_complex_diagram_persistence_from_off_file_example.py" "--no-diagram" "-f" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/data/points/tore3D_300.off" "-e" "0.25" "-d" "3")
set_tests_properties(rips_complex_diagram_persistence_from_off_file_example_py_test PROPERTIES  WORKING_DIRECTORY "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython")
add_test(rips_complex_from_points_example_py_test "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython" "/homes/rhu/Documents/phd_projects/kernelgformula/g_env/bin/python" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/cython/example/rips_complex_from_points_example.py")
set_tests_properties(rips_complex_from_points_example_py_test PROPERTIES  WORKING_DIRECTORY "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython")
add_test(simplex_tree_example_py_test "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython" "/homes/rhu/Documents/phd_projects/kernelgformula/g_env/bin/python" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/cython/example/simplex_tree_example.py")
set_tests_properties(simplex_tree_example_py_test PROPERTIES  WORKING_DIRECTORY "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython")
add_test(witness_complex_from_nearest_landmark_table_py_test "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython" "/homes/rhu/Documents/phd_projects/kernelgformula/g_env/bin/python" "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/cython/example/witness_complex_from_nearest_landmark_table.py")
set_tests_properties(witness_complex_from_nearest_landmark_table_py_test PROPERTIES  WORKING_DIRECTORY "/homes/rhu/Documents/phd_projects/TdaToolbox/2018-09-04-14-25-00_GUDHI_2.3.0/build/cython")
